== ri-analytics-rationale-miner image:https://img.shields.io/badge/License-EPL%202.0-blue.svg["EPL 2.0", link="https://www.eclipse.org/legal/epl-2.0/"]

This service was created as a result of the OpenReq project funded by the European Union Horizon 2020 Research and Innovation programme under grant agreement No 732463.

== Used Technologies
- Docker (→ https://www.docker.com/)
- SentiStrength (→ http://sentistrength.wlv.ac.uk/)

== Functionalities 
This API returns a json, containing the probability of an Amazon review containing a justification/decision/criteria/alternative/issue.

== How to Run The microservice
Run the following commands to start the microservice:

1) docker build -t ri-analytics-rationale-miner .

2) docker run "<PATH_TO_SentiStrength.jar>:/code/RationalyticsFramework/libs/SentiStrength.jar" -p 9704:9704 ri-analytics-rationale-miner

A full description of the the microservice can be found in swagger documentation below.

== Public APIs
The API is documented by using Swagger2:

- link:http://217.172.12.199/registry/#/services/ri-analytics-rationale-miner[Rendered Documentation]

== How to contribute
See OpenReq project contribution link:https://github.com/OpenReqEU/OpenReq/blob/master/CONTRIBUTING.md[Guidlines]

== License
Free use of this software is granted under the terms of the EPL version 2 (EPL2.0).